blank_issues_enabled: true
contact_links:
  - name: Bug report (use template)
    url: https://github.com/need4deed-org/fe/issues/new?template=bug_report.yml
    about: Open a pre-filled bug report using the bug_report template.
  - name: Feature request (use template)
    url: https://github.com/need4deed-org/fe/issues/new?template=feature_request.yml
    about: Open a feature request using the feature_request template.
  - name: Community / Support
    url: https://github.com/need4deed-org/.github#contributing
    about: Contribution guidelines and support information.
